'use client'

import { Aside } from '@/components/Aside'
import { ChatForm } from '@/components/CreatePrompt'
import { Header } from '@/components/Header'
import { useCallback, useState } from 'react'
import '../styles/globals.css'

type Props = {
  children: React.ReactNode
}

// export const metadata = {
//   title: 'Chat GPT',
//   description: 'Generated by create next app'
// }

const RootLayout: React.FC<Props> = ({ children }) => {
  const [isShowNavOpen, setIsShowNavOpen] = useState(true)

  const handleToggle = useCallback(() => {
    setIsShowNavOpen((prevShow) => !prevShow)
  }, [])

  return (
    <html lang='en'>
      <head>
        <title>Chat GPT</title>
      </head>
      <body>
        <div className='relative w-full flex h-screen bg-gptgray'>
          <Aside onToggle={handleToggle} isShowNavOpen={isShowNavOpen} />

          <div className={`flex flex-col w-full h-full`}>
            <main className='overflow-hidden flex flex-col relative h-full w-full'>
              <Header onToggle={handleToggle} />
              {children}
              <ChatForm />
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
export default RootLayout
