'use client'

import { Aside } from '@/components/Aside'
import { ChatForm } from '@/components/CreatePrompt'
import { Header } from '@/components/Header'
import { useCallback, useState } from 'react'
import '../styles/globals.css'

export const metadata = {
  title: 'Chat GPT',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  const [isShowNavOpen, setIsShowNavOpen] = useState(true)

  const handleToggle = useCallback(() => {
    setIsShowNavOpen((prevShow) => !prevShow)
  }, [])

  return (
    <html lang='en'>
      <head>
        <title>Chat GPT</title>
      </head>
      <body>
        <div className='relative w-full h-screen bg-gptgray'>
          <Aside onToggle={handleToggle} isShowNavOpen={isShowNavOpen} />

          <div
            className={`${
              isShowNavOpen ? 'lg:pl-80' : ''
            } flex flex-col flex-1 h-full`}
          >
            <main className='relative w-full'>
              <Header onToggle={handleToggle} />
              {children}
              <ChatForm />
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
